<a href="https://colab.research.google.com/github/limjunghyeon/ESAA_py/blob/main/23_03_10_ESAA_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

03 넘파이

:파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지.

●빠른 배열 연산속도 ( 루프X 대량 데이터 배열 연산 가능하게 함)

●저수준 언어 기반의 호환 API 제공
●편의성과 다양한 AOI 지원 측면에서 아쉬운 부분도 많음.


1. **array( )**
: 파이썬의 리스트와 같은 다양한 인자를 입력 받아 ndarray로 변환. 생성된 ndarray 배월의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 갖고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음


2. **np.array( )**
:ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환

  ndarray.shpe는 ndarray의 차원과 크기를 튜플 형태로 나타내 줌.

In [1]:
import numpy as np

In [5]:
#넘파이 array( ) 함수
array1=np.array([1,2,3])      #1차원
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2=np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3=np.array([[1,2,3]])       #1개의 로우와 3개의 칼럼으로 구성된 2차원 데이터.
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)


print('array1: {:0}차원, array: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array: 2차원, array3:  2차원


**ndarray의 데이터 타입**

:숫자, 문자, 불 값 등 모두 가능

ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능.
-> 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용.

ndarray내의 데이터 타입은 dtype 속성으로 확인 가능.

In [9]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [10]:
list2= [1,2, 'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


●**astype ( )**
: ndarray 내 데이터값의 타입 변경.
  ( )에 인자로 원하는 타입을 문자열로 지정.
  메모리 절약 위해 이용

In [14]:
#int 32 -> float64로 변환 / float64-> int32

array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


**ndarray 편리하게 생성**

-특정 크이와 차원 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우 사용하는 코드

●**arange( )**

:파이썬 표준 함수인 range( )와 유사. 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환.

●**zeros( )**

:함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shapeㄹㄹ 가진 ndarray를 반환.

●**ones( )**

:함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환. 함수 인자로 dtype를 정해주지 않으면 default로 float64 형의 데이터로 ndarray 채움.

In [20]:
##1.arange

sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

#default 함수 인자는 stop 값. 0부터 stop까지인 10에서 -1을 더한 9까지의 연속 숫자 값으로 구서된 1차원 ndarray 만듦.


##2. zero
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

##3. ones
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)



[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


ndarray의 차원과 크기를 변경하는 reshape( )

●**reshape( )**

:ndarray를 특정 차원 및 크기로 변환. 변환을 원하는 크기를 함수 인자로 부여.

reshape( )에 -1 값을 인자로 적용하면 원래 ndarray와 호환되는 새로운 shape로 변환

In [21]:
#0~9까지의 1차원 ndarray를 2로우x5칼럼, 5로우x2칼럼 형태로 2차원 ndarray로 변환

array1= np.arange(10)
print('array:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array:\n', array3)

array:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
array1.reshape(4,3)

ValueError: ignored

In [24]:
#인자 -1

array1=np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [26]:
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: ignored

In [28]:
#tolist( ) : ndarray는 위의 메서드를 이용해 리스트 자료형으로 변환 가능.

array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6= array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


**넘파이의 ndarray의 데이터 세트 서택하기 -indexing

:넘파이에서 ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 함.


1. 특정한 데이터만 추출

  : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환

2. 슬라이싱

  : 연속된 인덱스상의 ndarray를 추출하는 방식
  ':' 기호 사이에 시작 인덱스와 종료 인덱스 표시하면 시작 인덱스에서 종료 인덱스-1에 있는 데이터의 ndarray 반환


  3. 팬시 인덱싱
  
  : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환.

4. 불린 인덱싱

  : 특정 조건에 해당하는 여수인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환.



**단일 값 추출**


In [29]:
#1~9까지의 1차원 ndarray 생성
array1=np.arange(start=1, stop=10)
print('array1', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:', value)
print(type(value))

array1 [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [30]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [31]:
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [37]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)
      
print('(row=0,col=0) index 가르키는 값:', array2d[0,0])
print('(row=0,col=1) index 가르키는 값:', array2d[0,1])
print('(row=1,col=0) index 가르키는 값:', array2d[1,0])
print('(row=2,col=2) index 가르키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가르키는 값: 1
(row=0,col=1) index 가르키는 값: 2
(row=1,col=0) index 가르키는 값: 4
(row=2,col=2) index 가르키는 값: 9


**슬라이싱**

:  ':'기호를 이용해 연속한 데이터를 슬라이싱해서 추출 가능.

단일 데이터값 추출을 제외하고 스라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입.



In [39]:
array1=np.arange(start=1, stop=10)
array3= array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [41]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [43]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)


print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [44]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


**팬시 인덱싱**

:팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식.

In [46]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())

array4=array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


**불린 인덱싱**

:조건 필터링과 검색 동시에 가능.

In [49]:
array1d=np.arange(start=1, stop=10)
#[ ] 안에 array1d>5 Boolean indexing을 적용
array3= array1d[array1d >5]
print('array1d >5 불린 인덱싱 결과 값:', array3)


array1d >5

array1d >5 불린 인덱싱 결과 값: [6 7 8 9]


array([False, False, False, False, False,  True,  True,  True,  True])

In [51]:
boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

#위와 아래 동일

indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)


불린 인덱스로 필터링 결과: [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]


**행렬의 정렬**

●np.sort( )

:넘파이에서 sort( ) 호출. 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환.

●ndarray.sort( )

:행렬자체에서 sort( ) 호출. 원 행렬 자체를 정렬한 형태로 변환. 반환 값은 NOne

●argsort( )

:기존 원본 행렬의 원소에 대한 인덱스를 필요할 때, np.argsort( )를 이용. 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환

In [54]:
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort( )로 정렬
sort_array1=np.sort(org_array)
print('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)

#ndarray.sort( )로 정렬
sort_array2=org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [57]:
#내림차순으로 정렬 -> ex.np.sort( )[::-1]
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [59]:
array2d=np.array([[8,12], [7,1]])

sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [62]:
#np.argsort( )
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

#내림차순 -> np.sort()[::-1]

org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)


<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [63]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'kate', 'Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'kate']


선형대수 연산- 행렬 내적과 전치 행렬 구하기

●**np.dot()**

:행렬 내적(행렬의 곱)

●**transpose()**

:전치 행렬

In [70]:
#내적

A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,18],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)



#전치행렬
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬:\n', transpose_mat)

행렬 내적 결과:
 [[ 58  80]
 [139 194]]
A의 전치행렬:
 [[1 3]
 [2 4]]
